version: "3.3"
services:
    subscriber:
        depends_on:
            - "redis"
        build: services/subscriber
        environment:
            - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
    publisher:
        depends_on:
            - "redis"
        build: services/publisher
    mailman:
        build: services/mailman
        environment:
            - MAILGUN_USERNAME=${MAILGUN_USERNAME}
            - MAILGUN_PASSWORD=${MAILGUN_PASSWORD}
            - SENDER_EMAIL=${SENDER_EMAIL}
    newsfeed:
        build: services/newsfeed
        ports:
            - "3004:3004"
    redis:
        image: "redis:alpine"

    router:
        build: services/router
        ports:
            - "80:80"
    
    webapp:
        build: services/webapp
        depends_on:
            - "newsfeed"
            - "router"
        ports:
            - "3000:3000"