version: "3.9"
services:
    subscriber:
        depends_on:
            - "redis"
        build: services/subscriber
        ports:
            - 3001:3001
        environment:
            - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
    publisher:
        depends_on:
            - "redis"
        build: services/publisher
        ports:
            - 3002:3002
    mailman:
        build: services/mailman
        ports:
            - 3003:3003
        environment:
            - MAILGUN_USERNAME_SANDBOX=${MAILGUN_API_KEY}
            - MAILGUN_USERNAME_SANDBOX=${MAILGUN_USERNAME_SANDBOX}
            - MAILGUN_PASSWORD_SANDBOX=${MAILGUN_PASSWORD_SANDBOX}
            - MAIL_DOMAIN=${MAIL_DOMAIN}
            - SENDER_EMAIL=${SENDER_EMAIL}
    newsfeed:
        build: services/newsfeed
        ports:
            - 3004:3004
    redis:
        image: "redis:alpine"
        ports:
            - 6379:6379