name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Run the actions/checkout
      uses: actions/checkout@v2

    - name: Push to server
      uses: saadixl/Miazi@main
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: cd ${{ secrets.PROJECT_PATH }} && git pull && docker-compose up --build -d