name: Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Run the actions/checkout
      uses: actions/checkout@main

    - name: Push to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: whoami
          # cd ${{ secrets.PROJECT_PATH }}
          # git pull
          # docker-compose up --build -d
