name: Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Run the actions/checkout
      uses: actions/checkout@main

    - name: Push to server
      uses: ./
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          git pull
          docker-compose up --build -d